### ISSUE TITLE
KSampler_upscale seems to always use base model not Lora

### ISSUE THREAD

**Issue by ElliottLester** [JasonS09/comfy_sd_krita_plugin#31]
**Describe the bug**
When "Upscale second pass" is enabled the KSampler_upscale always references the base model 

**To Reproduce**
1. Run a workflow with a lora loader
2. Click on get workflow 
3. Notice Ksampler->model->"LoraLoader+1"
4. notice KSampler_upscale->model->"4"

**Comment by JasonS09** [comment]
Hello! Thanks for pointing this out. Can you check if it works now?

**Comment by ElliottLester** [comment]
@JasonS09  yeah that seems to fix it thanks :)
