### ISSUE TITLE
No preview displayed?

### ISSUE THREAD

**Issue by space-nuko** [JasonS09/comfy_sd_krita_plugin#33]
**Describe the bug**
As of recent ComfyUI versions there is a built-in latent preview method that works via websockets, however it seems like it doesn't show up in the `Live Preview` window?

Here is an example of how to implement it

https://github.com/comfyanonymous/ComfyUI/blob/e73ec8c4dad72650e94a5c9fdad574b2d2dae66f/web/scripts/api.js#L82-L107

**To Reproduce**
1. Click `Start txt2img`
2. No preview displayed

**Desktop (please complete the following information):**
 - OS: Windows
 - WebUI commit revision 9906e3efe31a0fc399262766da33c210fb4e8215
 - Extension commit revision 43b90b7902720ca8eed65df61c7b5b2e3ddc4e2f

**Comment by JasonS09** [comment]
Yes, [Live Preview hasn't been implemented](https://github.com/JasonS09/comfy_sd_krita_plugin/issues/8). It's nice if there is a way to implement it now, however I don't think it's a priority and honestly I don't have much interest in making it work (I'm not planning to). That said, anyone is welcome to make a PR with the proper implementation, I will gladly accept it.
