### ISSUE TITLE
Error when trying to "load prompt from layer"

### ISSUE THREAD

**Issue by 42degrees** [JasonS09/comfy_sd_krita_plugin#37]
I have not used Krita before today and I installed it only to try to use this plugin, so this could be something I did wrong in the installation process for the plugin.  I've been able to get img2img working, but when I load a PNG and then select "Load Prompt from Layer" I get the error below.  I tested this with several images.  I tested each image by dropping it onto ComfyUI and they all load the workflow just fine.  I assume that the prompt is being pulled out of the workflow, so I tried several different workflows, including the default simple workflow, but they all fail.  From the final error, "Expecting value: line 1 column 1 (char 0)" my assumption is that it's not getting the JSON from the image at all.  Here is the full error, with a screenshot below, if that helps.

JSONDecodeError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Wed Nov 15 11:40:48 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\Scott Gartner\AppData\Roaming\krita\pykrita\krita_comfy\pages\img_base.py in <lambda>()
  107         self.custom_workflow.cfg_connect()
  108         self.prompt_layout.cfg_connect()
  109         self.prompt_layer_load.released.connect(lambda: self.update_prompt(script.prompt_from_selection()))
  110         self.seed_layout.cfg_connect()
  111         self.sampler_layout.cfg_connect()
self = <krita_comfy.pages.img2img.Img2ImgPage object>
self.prompt_layer_load = <PyQt5.QtWidgets.QPushButton object>
self.prompt_layer_load.released = <bound PYQT_SIGNAL released of QPushButton object>
self.prompt_layer_load.released.connect = <built-in method connect of PyQt5.QtCore.pyqtBoundSignal object>
self.update_prompt = <bound method SDImgPageBase.update_prompt of <krita_comfy.pages.img2img.Img2ImgPage object>>
global script = <krita_comfy.script.Script object>
script.prompt_from_selection = <bound method Script.prompt_from_selection of <krita_comfy.script.Script object>>

 C:\Users\Scott Gartner\AppData\Roaming\krita\pykrita\krita_comfy\script.py in prompt_from_selection(self=<krita_comfy.script.Script object>)
  118             return None
  119 
  120         prompt_info = PromptBase.from_json(self.node.name())
  121         if not prompt_info:
  122             self.status_changed.emit(ERR_MISSING_PROMPT)
prompt_info undefined
global PromptBase = <class 'krita_comfy.prompt.PromptBase'>
PromptBase.from_json = <function PromptBase.from_json>
self = <krita_comfy.script.Script object>
self.node = <PyKrita.krita.Node object>
self.node.name = <built-in method name of Node object>

 C:\Users\Scott Gartner\AppData\Roaming\krita\pykrita\krita_comfy\prompt.py in from_json(text='Background')
  200         keys = get_members(PromptBase)
  201         # Skip text until json starts
  202         prompt_data = json.loads(text[text.find('{'):])
  203         for k in keys:
  204             setattr(prompt, k, prompt_data[k])
prompt_data undefined
global json = <module 'json' from 'C:\\Program Files\\Krita (x64)\\python\\python310.zip\\json\\__init__.pyc'>
json.loads = <function loads>
text = 'Background'
text.find = <built-in method find of str object>

 C:\Program Files\Krita (x64)\json\__init__.py in loads(s='d', cls=None, object_hook=None, parse_float=None, parse_int=None, parse_constant=None, object_pairs_hook=None, **kw={})

 C:\Program Files\Krita (x64)\json\decoder.py in decode(self=<json.decoder.JSONDecoder object>, s='d', _w=<built-in method match of re.Pattern object>)

 C:\Program Files\Krita (x64)\json\decoder.py in raw_decode(self=<json.decoder.JSONDecoder object>, s='d', idx=0)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    __cause__ = None
    __class__ = <class 'json.decoder.JSONDecodeError'>
    __context__ = StopIteration(0)
    __delattr__ = <method-wrapper '__delattr__' of JSONDecodeError object>
    __dict__ = {'colno': 1, 'doc': 'd', 'lineno': 1, 'msg': 'Expecting value', 'pos': 0}
    __dir__ = <built-in method __dir__ of JSONDecodeError object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of JSONDecodeError object>
    __format__ = <built-in method __format__ of JSONDecodeError object>
    __ge__ = <method-wrapper '__ge__' of JSONDecodeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of JSONDecodeError object>
    __gt__ = <method-wrapper '__gt__' of JSONDecodeError object>
    __hash__ = <method-wrapper '__hash__' of JSONDecodeError object>
    __init__ = <bound method JSONDecodeError.__init__ of JSONDe...ror('Expecting value: line 1 column 1 (char 0)')>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of JSONDecodeError object>
    __lt__ = <method-wrapper '__lt__' of JSONDecodeError object>
    __module__ = 'json.decoder'
    __ne__ = <method-wrapper '__ne__' of JSONDecodeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <bound method JSONDecodeError.__reduce__ of JSON...ror('Expecting value: line 1 column 1 (char 0)')>
    __reduce_ex__ = <built-in method __reduce_ex__ of JSONDecodeError object>
    __repr__ = <method-wrapper '__repr__' of JSONDecodeError object>
    __setattr__ = <method-wrapper '__setattr__' of JSONDecodeError object>
    __setstate__ = <built-in method __setstate__ of JSONDecodeError object>
    __sizeof__ = <built-in method __sizeof__ of JSONDecodeError object>
    __str__ = <method-wrapper '__str__' of JSONDecodeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = True
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ('Expecting value: line 1 column 1 (char 0)',)
    colno = 1
    doc = 'd'
    lineno = 1
    msg = 'Expecting value'
    pos = 0
    with_traceback = <built-in method with_traceback of JSONDecodeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\Scott Gartner\AppData\Roaming\krita\pykrita\krita_comfy\pages\img_base.py", line 109, in <lambda>
    self.prompt_layer_load.released.connect(lambda: self.update_prompt(script.prompt_from_selection()))
  File "C:\Users\Scott Gartner\AppData\Roaming\krita\pykrita\krita_comfy\script.py", line 120, in prompt_from_selection
    prompt_info = PromptBase.from_json(self.node.name())
  File "C:\Users\Scott Gartner\AppData\Roaming\krita\pykrita\krita_comfy\prompt.py", line 202, in from_json
    prompt_data = json.loads(text[text.find('{'):])
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

![image](https://github.com/JasonS09/comfy_sd_krita_plugin/assets/1676142/69316d37-d900-48a5-a730-242094ded506)

**Comment by JasonS09** [comment]
> I've been able to get img2img working, but when I load a PNG and then select "Load Prompt from Layer"

I think you're misunderstanding the "Load Prompt from Layer" functionality. It's not for loading the workflow from a Comfy image. 

This button will only work when you have a group layer selected, product of a previous generation. It's intended to reproduce all the data of that specific generation in your plugin so you can do it again without having to manually configure it.

The plugin automatically crafts the required workflow for each mode when you press the "Start" button. If you want to inject more complex workflows (a totally optional feature), you can do that in your "workflow" tab, although by the way how ComfyUI handles the nodes with ids can be a bit tricky. I suggest reading the wiki of this repo to clear your doubts.

**Comment by 42degrees** [comment]
Thanks Jason, I appreciate your clearing that up for me.  Though I was confused about what it was supposed to do, it still threw an exception instead of telling me what I did wrong (even if I thought it was going to do something else).

**Comment by JasonS09** [comment]
Yes, you're right. Exception should be handled now.
