### ISSUE TITLE
New user questions

### ISSUE THREAD

**Issue by iChristGit** [JasonS09/comfy_sd_krita_plugin#38]
Hey!
I have a 3090 and I tried the new live feature, it works but ive seen it can generate a picture every half a second on other machines, I am using the automatic server and I can see it using LCM 6 steps, also in settings i set the gpu to high.
Is there a way to speed it up? Maybe doing a local install of comfyui with optimization?

How fast are your live previews with 3090/3080?

**Comment by JasonS09** [comment]
Hello. I'm not sure I understand your question. There is no live feature in this plugin if I understand correctly. Maybe you're posting in the wrong repo?

**Comment by iChristGit** [comment]
> Hello. I'm not sure I understand your question. There is no live feature in this plugin if I understand correctly. Maybe you're posting in the wrong repo?

You are correct, il close the issue sorry for the confusion
