### ISSUE TITLE
Particular demand

### ISSUE THREAD

**Issue by Mandraw** [JasonS09/comfy_sd_krita_plugin#4]
I'm sorry to open this here, but saw no other way to contact you otherwise.

To what I understand you are switching your focus from A1111 to ComfyUI.

That's understandable, I also think Comfy has a more robust base. I would really switch to comfyUI as a daily driver but... as of of now comfyUI doesn't live up to the comfy part of it's name, at least for me.

I've forked your fork of interpause, since yours was the last working ( as of one week ago ) version for using A1111 in Krita

Unless you plan on continuing that fork ( but if you are that would be really, really cool ) I was thinking on picking it up... I just have no idea where to start from, so I came here to ask for a few pointers.

So yeah... here is the only place I can contact you. Also do you have a ko-fi or something ? I wouldn't mind tipping for services rendered to the community ^^

**Comment by JasonS09** [comment]
I don't think I will be working on the Automatic1111 version anymore, so you're free to fork it and pick it up! That said, I don't mind helping you and clarifying your questions. 

I'm not much of a social network guy but you can contact me on Reddit (u/RangerRocket09) or Discord (piratewolf). We can chat there. Also, I recently opened a Buy Me A Coffee account. It's linked on the Readme.md file of this repo, actually. A bit of a tip is appreciated!

**Comment by Mandraw** [comment]
Right now acclimating myself to the repo ( and python )
Will send you a message on discord then when I get to it and get stuck, thanks !
