### ISSUE TITLE
Add the last steps in the install instruction to enable the plugin

### ISSUE THREAD

**Issue by fernicar** [JasonS09/comfy_sd_krita_plugin#5]
I would like to ask last steps to be added in the readme:

First save your custom Workspace, it will change after we are done.

Go to Settings > Configure Krita. (It will open the Config menu.)
On the Left panel select "Python Plugin Manager"
Add a check to "ComfyUI Plugin" in the checkbox list on the left panel.
Click OK to close "Config menu".
After restarting Krita your Workspace should be populated by new dockers, you can show/hide them in the Settings > Dockers checklist.
Rearrange your Workspace and save it, example "ComfyUI".

**Comment by JasonS09** [comment]
Added. Thanks for the contribution!
