### ISSUE TITLE
Live Preview may be broken

### ISSUE THREAD

**Issue by coreyryanhanson** [JasonS09/comfy_sd_krita_plugin#8]
**Describe the bug**

**To Reproduce**
Image generation both using default latent previews and TAESD does not create any previews. During prompt execution, the status says "Executing Prompt... (0 in queue)".

**Screenshots**
![Screenshot from 2023-07-31 12-12-31](https://github.com/JasonS09/comfy_sd_krita_plugin/assets/17171838/56bd798f-670f-4b5d-8ebb-27b43d849ddd)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - ComfyUI commit revision: 4a77fcd6ab01d69e18c384faa29ae1c3d02237f3
 - Extension commit revision: 08267735ee15a6fcd8287745c1aa9f560520d062

**Comment by JasonS09** [comment]
Hello. Live preview is not a feature that has been implemented, even though there is a tab remaining from it's previous version. I might consider implementing it if requested, but not really sure how to.

**Comment by coreyryanhanson** [comment]
That makes sense. I wish I could help, but after looking at the code all I have is a general idea, but don't quite know the finer details of Krita's plugin API to effectively implement it.

It appears there is a method called [set_progress_bar_global_hook](https://github.com/comfyanonymous/ComfyUI/blob/076d2db60ff8483c9b2cccc26541d6237be14ebc/comfy/utils.py#L360C5-L360C33) that gives access to ComfyUI's progress bar and preview images. I'm guessing the plugin's [PreviewPage  class](https://github.com/JasonS09/comfy_sd_krita_plugin/blob/9019de92a32b9e098dfd171f385288263b3d294f/frontends/krita/krita_comfy/pages/preview.py#L8) would need to be refactored to handle the arguments passed to the [update_absolute method](https://github.com/comfyanonymous/ComfyUI/blob/076d2db60ff8483c9b2cccc26541d6237be14ebc/comfy/utils.py#L371). I could be wrong and be missing something important, but it seems to be the most promising way I think.

**Comment by JasonS09** [comment]
> That makes sense. I wish I could help, but after looking at the code all I have is a general idea, but don't quite know the finer details of Krita's plugin API to effectively implement it.
> 
> It appears there is a method called [set_progress_bar_global_hook](https://github.com/comfyanonymous/ComfyUI/blob/076d2db60ff8483c9b2cccc26541d6237be14ebc/comfy/utils.py#L360C5-L360C33) that gives access to ComfyUI's progress bar and preview images. I'm guessing the plugin's [PreviewPage class](https://github.com/JasonS09/comfy_sd_krita_plugin/blob/9019de92a32b9e098dfd171f385288263b3d294f/frontends/krita/krita_comfy/pages/preview.py#L8) would need to be refactored to handle the arguments passed to the [update_absolute method](https://github.com/comfyanonymous/ComfyUI/blob/076d2db60ff8483c9b2cccc26541d6237be14ebc/comfy/utils.py#L371). I could be wrong and be missing something important, but it seems to be the most promising way I think.

Problem is that, while developing, I couldn't find a ComfyUI endpoint that could be used for that, so not sure if it's possible.
